import { library, config } from "@fortawesome/fontawesome-svg-core";
import {
  faHouse,
  faWallet,
  faPiggyBank,
  faPeopleGroup,
  faStore,
  faList,
  faGear,
  faCircleQuestion,
  faRightFromBracket,
  faBars,
  faMagnifyingGlass,
  faBell,
  faPlus,
  faArrowDown,
  faArrowUp,
  faBuildingColumns,
  faChartLine,
  faChartPie,
  faClipboardList,
  faUsers,
  faBuilding,
  faCog,
  faEye,
  faEyeSlash,
  faEnvelope,
  faLock,
  faPhone,
  faUser,
  faArrowRight,
  faCheck,
  faTimes,
  faExclamationTriangle,
  faInfoCircle,
  faCalendar,
  faFilter,
  faDownload,
  faEdit,
  faTrash,
  faEllipsisVertical,
  faCoins,
  faMoneyBillWave,
  faHandHoldingDollar,
  faChartBar,
  faShoppingCart,
  faExchangeAlt,
  faCreditCard,
  faTachometerAlt,
  faSearch,
  faSortUp,
  faSortDown,
  faXmark,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faLocationDot,
  faCar,
  faHouseChimney,
  faStar,
} from "@fortawesome/free-solid-svg-icons";
import {
  faFacebook,
  faTwitter,
  faInstagram,
  faGoogle,
  faApple,
} from "@fortawesome/free-brands-svg-icons";

config.autoAddCss = false;

library.add(
  faHouse, faWallet, faPiggyBank, faPeopleGroup, faStore,
  faList, faGear, faCircleQuestion, faRightFromBracket,
  faBars, faMagnifyingGlass, faBell, faPlus, faArrowDown,
  faArrowUp, faBuildingColumns, faChartLine, faChartPie,
  faClipboardList, faUsers, faBuilding, faCog, faEye,
  faEyeSlash, faEnvelope, faLock, faPhone, faUser,
  faArrowRight, faCheck, faTimes, faExclamationTriangle,
  faInfoCircle, faCalendar, faFilter, faDownload,
  faEdit, faTrash, faEllipsisVertical, faCoins,
  faMoneyBillWave, faHandHoldingDollar, faChartBar,
  faShoppingCart, faExchangeAlt, faCreditCard,
  faTachometerAlt, faSearch, faSortUp, faSortDown,
  faXmark, faChevronLeft, faChevronRight, faChevronDown,
  faLocationDot, faCar, faHouseChimney, faStar,
  faFacebook, faTwitter, faInstagram, faGoogle, faApple,
);
