import { library, config } from "@fortawesome/fontawesome-svg-core";
import {
  faHouse,
  faHome,
  faWallet,
  faPiggyBank,
  faPeopleGroup,
  faStore,
  faList,
  faGear,
  faCircleQuestion,
  faRightFromBracket,
  faBars,
  faMagnifyingGlass,
  faBell,
  faPlus,
  faPlusCircle,
  faArrowDown,
  faArrowUp,
  faBuildingColumns,
  faChartLine,
  faChartPie,
  faClipboardList,
  faUsers,
  faBuilding,
  faCog,
  faEye,
  faEyeSlash,
  faEnvelope,
  faLock,
  faPhone,
  faUser,
  faArrowRight,
  faCheck,
  faTimes,
  faExclamationTriangle,
  faInfoCircle,
  faCalendar,
  faFilter,
  faDownload,
  faEdit,
  faTrash,
  faEllipsisVertical,
  faCoins,
  faMoneyBillWave,
  faHandHoldingDollar,
  faChartBar,
  faShoppingCart,
  faShoppingBag,
  faExchangeAlt,
  faCreditCard,
  faTachometerAlt,
  faSearch,
  faSortUp,
  faSortDown,
  faXmark,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faLocationDot,
  faMapMarkerAlt,
  faCar,
  faHouseChimney,
  faStar,
  faSignOutAlt,
  faBullhorn,
  faLayerGroup,
  faQuestionCircle,
  faBinoculars,
  faMoneyBillTransfer,
  faArrowRightArrowLeft,
  faGlobe,
  faShieldHalved,
  faBan,
  faCircleCheck,
  faCircleXmark,
  faClockRotateLeft,
  faUserPlus,
  faFileInvoice,
  faImage,
  faTableColumns,
  faGripVertical,
  faPause,
  faPlay,
  faRotate,
  faHeart,
} from "@fortawesome/free-solid-svg-icons";
import {
  faFacebook,
  faFacebookF,
  faTwitter,
  faInstagram,
  faGoogle,
  faApple,
  faLinkedinIn,
} from "@fortawesome/free-brands-svg-icons";

config.autoAddCss = false;

library.add(
  faHouse, faHome, faWallet, faPiggyBank, faPeopleGroup, faStore,
  faList, faGear, faCircleQuestion, faRightFromBracket,
  faBars, faMagnifyingGlass, faBell, faPlus, faPlusCircle,
  faArrowDown, faArrowUp, faBuildingColumns, faChartLine,
  faChartPie, faClipboardList, faUsers, faBuilding, faCog,
  faEye, faEyeSlash, faEnvelope, faLock, faPhone, faUser,
  faArrowRight, faCheck, faTimes, faExclamationTriangle,
  faInfoCircle, faCalendar, faFilter, faDownload,
  faEdit, faTrash, faEllipsisVertical, faCoins,
  faMoneyBillWave, faHandHoldingDollar, faChartBar,
  faShoppingCart, faShoppingBag, faExchangeAlt, faCreditCard,
  faTachometerAlt, faSearch, faSortUp, faSortDown,
  faXmark, faChevronLeft, faChevronRight, faChevronDown,
  faLocationDot, faMapMarkerAlt, faCar, faHouseChimney, faStar,
  faSignOutAlt, faBullhorn, faLayerGroup, faQuestionCircle, faBinoculars,
  faFacebook, faFacebookF, faTwitter, faInstagram,
  faGoogle, faApple, faLinkedinIn,
  faMoneyBillTransfer, faArrowRightArrowLeft, faGlobe,
  faShieldHalved, faBan, faCircleCheck, faCircleXmark,
  faClockRotateLeft, faUserPlus, faFileInvoice, faImage,
  faTableColumns, faGripVertical, faPause, faPlay, faRotate,
  faHeart,
);
